version: "3.5"

services:
  app:
    image: ghcr.io/spam-chka/spam-chka
    ports:
      - "8080:3000"
    env_file:
      - .env
    networks:
      - main
    deploy:
      resources:
        limits:
          memory: 100M

  mongo:
    image: mongo
    networks:
      - main
    deploy:
      resources:
        limits:
          memory: 350M

  redis:
    image: redis
    networks:
      - main
    deploy:
      resources:
        limits:
          memory: 50M

networks:
  main: { }
