version: "3.5"

services:
  app:
    image: ghcr.io/spam-chka/spam-chka
    ports:
      - "8080:3000"
    env_file:
      - .env
    networks:
      - main

  mongo:
    image: mongo
    networks:
      - main

  redis:
    image: redis
    networks:
      - main

networks:
  main: { }
